spring.application.name=task-api
spring.mongodb.uri=mongodb://localhost:27017/task_db?directConnection=true
server.port=8080
server.address=0.0.0.0
spring.graphql.schema.file-extensions=.graphqls,.gqls,.graphql
spring.graphql.graphiql.enabled=true
logging.level.org.springframework.graphql=DEBUG

# CORS for GraphQL endpoint
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS
spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allow-credentials=false